const HomeController = require('../controllers/HomeController')
const UserController = require('../controllers/UserController')
const CityController = require('../controllers/CityController')
const GroupController = require('../controllers/GroupController')
const MembershipController = require('../controllers/MembershipController')
const EventController = require('../controllers/EventController')
const BoardController = require('../controllers/BoardController')

module.exports = function(app){
    app.get('/', HomeController.Index)
    app.get('/login', UserController.LoginForm)
    app.post('/login', UserController.Login)
    app.get('/logout', UserController.Logout)

    app.get('/users', UserController.Index)
    app.get('/users/create', UserController.CreateForm)
    app.post('/users/create', UserController.Create)
    app.get('/users/edit/:id', UserController.EditForm)
    app.put('/users/edit/:id', UserController.Edit)
    app.delete('/users/delete/:id', UserController.Delete)

    app.get('/cities', CityController.Index)
    app.get('/cities/create', CityController.CreateForm)
    app.post('/cities/create', CityController.Create)
    app.get('/cities/edit/:id', CityController.EditForm)
    app.put('/cities/edit/:id', CityController.Edit)
    app.delete('/cities/delete/:id', CityController.Delete)

    app.get('/groups', GroupController.Index)
    app.get('/groups/create', GroupController.CreateForm)
    app.post('/groups/create', GroupController.Create)
    app.get('/groups/edit/:id', GroupController.EditForm)
    app.put('/groups/edit/:id', GroupController.Edit)
    app.delete('/groups/delete/:id', GroupController.Delete)
    //app.get('/groups/grant/:id', GroupController.GrantForm)

    app.get('/memberships', MembershipController.Index)
    app.get('/memberships/:userid', MembershipController.List)
    app.get('/memberships/:userid/create', MembershipController.CreateForm)
    app.post('/memberships/:userid/create', MembershipController.Create)
    app.get('/memberships/:userid/edit/:id', MembershipController.EditForm)
    app.put('/memberships/:userid/edit/:id', MembershipController.Edit)
    app.delete('/memberships/:userid/delete/:id', MembershipController.Delete)

    app.get('/events', EventController.Index)
    app.get('/events/:id/reservations', EventController.Reservations)
    app.put('/events/:eventid/reservations/:id/approved', EventController.ReservationApproved)
    app.get('/events/create', EventController.CreateForm)
    app.post('/events/create', EventController.Create)
    app.get('/events/edit/:id', EventController.EditForm)
    app.put('/events/edit/:id', EventController.Edit)
    app.delete('/events/delete/:id', EventController.Delete)

    app.get('/boards', BoardController.Index)
    app.get('/boards/create', BoardController.CreateForm)
    app.post('/boards/create', BoardController.Create)
    app.get('/boards/edit/:id', BoardController.EditForm)
    app.put('/boards/edit/:id', BoardController.Edit)
    app.delete('/boards/delete/:id', BoardController.Delete)

}
